#!/bin/bash
# Connect to bluetooth device using bluetoothctl

DEVICE="F4:4E:FC:78:57:22"

sudo service bluetooth start

bluetoothctl power on
bluetoothctl agent on
bluetoothctl default-agent
bluetoothctl connect $DEVICE
