# --- Volume ---
UP      add volume 5        # increase volume
DOWN    add volume -5       # decrease volume
# --- Subtitle ---
s     cycle sub            # cycle subtitle tracks
v     cycle sub-visibility # toggle subtitles on/off

# --- Audio track ---
a     cycle audio          # cycle audio tracks

# --- Playback ---
SPACE     cycle pause          # pause / play
f         cycle fullscreen     # toggle fullscreen
q         quit                 # quit mpv


