#!/bin/bash
# Simple Wi-Fi switcher for home/office
# Requires: wpa_supplicant, dhcpcd
IFACE="wlan0"

# clear previous records
reset_iface() {
    sudo killall wpa_supplicant dhcpcd 2>/dev/null
    sudo pkill dhcpcd 2>/dev/null

    sudo ip link set $IFACE down
    sleep 1
    sudo ip link set $IFACE up
    sleep 1
}

case "$1" in

moto)
    echo "[*] Connecting to Moto WiFi..."
    reset_iface
    sudo wpa_supplicant -B -i $IFACE -c /etc/wpa_supplicant/wpa_supplicant-moto.conf
    sleep 2
    sudo dhcpcd $IFACE
    ;;
putti)
    echo "[*] Connecting to Vivo WiFi..."
    reset_iface
    sudo wpa_supplicant -B -i $IFACE -c /etc/wpa_supplicant/wpa_supplicant-putti.conf
    sleep 2
    sudo dhcpcd $IFACE
    ;;
cable)
    echo "[*] Connecting to Cable WiFi..."
    reset_iface
    sudo wpa_supplicant -B -i $IFACE -c /etc/wpa_supplicant/wpa_supplicant-cable.conf
    sleep 2
    sudo dhcpcd $IFACE
    ;;
*)
    echo "Usage: wifi {moto|putti|cable}"
    ;;
esac
