# Force stereo audio output for Bluetooth speakers
audio-channels=stereo
# Allow the volume to be boosted up to 200%
volume-max=200

# Set the default startup volume to 130%
volume=100
# Boost quiet audio/speech while capping loud explosions
af=lavfi=[acompressor=ratio=4:makeup=2]
